services:
  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "7777:7777"
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./db:/usr/src/app/db
      - ./docs-config.local.yaml:/usr/src/app/docs-config.yaml
