FROM node:16.14.0-alpine3.15

WORKDIR /usr/src/app
RUN apk add --no-cache git gcc g++ python make musl-dev

COPY package.json yarn.lock ./

RUN yarn install --prod

COPY . .

RUN yarn compile

CMD ["yarn", "start"]
